### ISSUE TITLE
Booting/linux-bootstrap-1.md 번역 진행중

### ISSUE THREAD

**Issue by producer82** [junsooo/linux-insides-ko#10]
미번역된 부분을 220번 줄까지 번역할 예정에 있습니다.

**Comment by junsooo** [comment]
혹시 뒷부분도 진행하시나요?

**Comment by producer82** [comment]
> 혹시 뒷부분도 진행하시나요?

일단 부트스트랩 1장은 총대를 맸으니까 끝까지 해 볼 생각입니다.
고등학생이라 시간이 없어서 금방 될지는 모르겠지만요...

**Comment by junsooo** [comment]
네 부담갖지 말고 천천히 해주세요!
바쁘시면 제가 할 수도 있습니다 :) 언제든 알려주세요.

**Comment by junsooo** [comment]
완료한 번역이므로 close 하겠습니다.
