### ISSUE TITLE
Concepts/linux-cpu-1.md 번역 진행중

### ISSUE THREAD

**Issue by biyott** [junsooo/linux-insides-ko#13]
Concepts/linux-cpu-1.md
Concepts/linux-cpu-2.md
Concepts/linux-cpu-3.md
Concepts/linux-cpu-4.md
전부분을 번역하려 합니다.

**Comment by biyott** [comment]
pull request했습니다. 수락되면 korean-contributors.md에 추가하도록 하겠습니다 :)

**Comment by junsooo** [comment]
네. 수락했습니다 :)

**Comment by biyott** [comment]
감사합니다. 열심히 할게요!

**Comment by biyott** [comment]
Concepts/linux-cpu-1.md 번역을 마치고 pull한줄 알았는데 오늘 보니 안됐군요.
contibute이 처음이라 실수들이 있네요. ㅠ
집에 가서 마져 올리겠습니다. ㅎㅎ

**Comment by junsooo** [comment]
네 수고 많으셨습니다. 해당 issue close 하겠습니다.
