### ISSUE TITLE
질문 있습니다

### ISSUE THREAD

**Issue by casionwoo** [junsooo/linux-insides-ko#15]
여기는 번역만하고 공부한거 올리는거는 안되는겁니까?

우리도 저렇게 공부해서 올리면 참 좋기는 할텐데요.

**Comment by junsooo** [comment]
안녕하세요, casionwoo 님.

casionwoo 님의 의견에 매우 공감합니다.
그런데 현재 레포지토리는 기존 linux-insides의 한국어 번역 레포지토리이므로,
casionwoo 님께서 새로 운영체제 공부에 대한 레포지토리를 만드시고 이에 대해 알려주시면
해당 레포지토리에 직접 공유할 내용을 올릴 수 있도록 하겠습니다.

궁금하신 사항이 있으시면 알려주세요. 감사합니다.

**Comment by casionwoo** [comment]
네 알겠습니다.
