### ISSUE TITLE
Theory/linux-theory-1.md 번역 진행중

### ISSUE THREAD

**Issue by gggrgrgrr** [junsooo/linux-insides-ko#20]

**Comment by gggrgrgrr** [comment]
Theory/linux-theory-1.md  현재 겹치는 부분 없는것 같아서 번역 진행해도 되겠습니까?

**Comment by junsooo** [comment]
네 그렇게 해주세요. 감사합니다

**Comment by gggrgrgrr** [comment]
제가 완벽히 이해한 상태가아니라 번역을 하면 해가 될 것 같아 linux-theory-1 번역 포기합니다

죄송합니다
