### ISSUE TITLE
Theory/linux-theory-2.md 번역  

### ISSUE THREAD

**Issue by byounghoonkim** [junsooo/linux-insides-ko#21]
개인적으로 ELF 에 대해 관심이 있어서 Theory/linux-theory-2.md 부분을 번역하고 있습니다.
중복되지 않으면 다 번역한 후 풀리퀘스트 드리도록 하겠습니다.

**Comment by junsooo** [comment]
네, 안녕하세요.
그렇게 해주세요. 감사합니다

**Comment by junsooo** [comment]
완료된 이슈이므로 close 하겠습니다.
